/* One selected October night at a time; its only CSV button is in the tab header. */
function fillOctober(night){
  const O=D.october;if(!O)return;
  const rows=O.rows.filter(r=>r.night===night),meta=O.nights[night];
  const standards=O.standards.filter(r=>r.night===night).map(r=>`${esc(r.name)} ${r.start_pdt.slice(11,16)}–${r.end_pdt.slice(11,16)} (${r.exposures} × ${r.seconds_each} s initial; check counts)`).join('; ');
  const header=`<p><b>2 × 300 s · 1.5″ slit · 2 × 3 binning · 2 min overhead.</b> Moon ≥40° throughout every visit.</p><p class="small muted">PDT ${meta.dusk_pdt.slice(11,16)}–${meta.dawn_pdt.slice(11,16)} · Moon ${Math.round(meta.moon_illumination_percent)}% · ${Math.round(meta.remaining_minutes)} min spare after 20 min for standards.</p><details class="night-notes"><summary>Standards, timing and JWST notes</summary><p>${standards}.</p><p class="plot-note">The dawn sequence is tight: protect JWST visits if running late. The CSV specifies order and settings; follow the times below to preserve gaps. Magnitudes are archival, generally through 2025. P11530 is Moon-blocked in October and retains its September spectrum. UGC 03601 is scheduled October 26; P9506, P10381 and P9694 on October 27. Alternatives are in each target's card.</p></details>`;
  const table=`<div class="table-scroll"><table><thead><tr>${['#','VISIT (PDT)','UTC START','TARGET','JWST','RA (H:M:S)','DEC (D:M:S)','CACHED r','MAX X','MIN MOON','PRIORITY / NOTES'].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr data-october-target="${esc(r.name)}" class="${r.jwst_id?'seq':''}"><td>${r.order}</td><td class="mono">${r.start_pdt.slice(11,16)}–${r.end_pdt.slice(11,16)}</td><td>${r.start_utc.slice(11,16)}</td><td><a href="#card-${esc(r.name)}">${esc(r.name)}</a></td><td>${esc(r.jwst_id||'—')}</td><td class="mono">${esc(r.ra_hms)}</td><td class="mono">${esc(r.dec_dms)}</td><td>${fmt(+r.r_adopted,2)}</td><td>${fmt(+r.airmass_max_actual,2)}</td><td>${fmt(+r.moon_min,1)}°</td><td class="october-notes"><b>${esc(r.priority_reason)}</b>${r.flags?'<br>'+esc(r.flags):''}</td></tr>`).join('')}</tbody></table></div>`;
  $('october').innerHTML=header+table;
}
